### PR TITLE
docs: submit snippets over https

### PR DESCRIPTION
**Pull request by tsvetomir**
We can now close the loop and get rid of this warning in Firefox:

image

### CODE REVIEW

**Comment by gyoshev** [comment]
I'd love to, but `gulp docs` serves over http ☹️ With this change, local demos cannot be opened in plunker, and it also won't work when testing the k2-site locally. Perhaps it would be more appropriate to use the `window.location.protocol` to handle both cases, and keep the CORS headers as they are?

**Comment by tsvetomir** [comment]
Agreed :+1:

**Comment by gyoshev** [comment]
*That moment when you merge a PR and realize that it won't publish a new version...*

Oh well, we'll get this after #104 😄

**Comment by tsvetomir** [comment]
A well planted _lurker feature_ on my side. Straight from "Evading the changelog 101" book.

**Pull request merged**
